# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: myAgentPool

variables: 
  azureServiceConnectionId: 'myServiceConnection'
  webAppName: 'myappenis12'
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
  - stage: Build
    displayName: Build stage
    jobs:
    - job: Build
      pool: myAgentPool
      steps:
        - script: |
            export PATH=$HOME/.local/bin:$PATH
            python3 -m pip install -r requirements.txt
          workingDirectory: $(projectRoot)
          displayName: 'Step - Install requiremets'

        - task: ArchiveFiles@2
          displayName: 'Step - ArchiveFiles'
          inputs:
            rootFolderOrFile: '$(projectRoot)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true  
          
        - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          displayName: 'Step - Upload Artifact'
          artifact: drop  